version: '3.7'

# Services
services:
  # API backend
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: always
    environment:
      - TZ=Asia/Tokyo
    networks:
      - hcapp-network
  client-server:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://178.128.16.172:5050"
    ports:
      - "80:3000"
    restart: always
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - api-server
    networks:
      - hcapp-network
networks:
  hcapp-network: